import foneP2LehMox from "../assets/imgs/fone com fio lehmox.png";
import foneP2KapBom from "../assets/imgs/fone com fio lehmox.png";
import foneBluetoothStarMega from "../assets/imgs/Fone Bluetooth ST-158 Starmega - Preto-228x228.png";
import foneBluetoothStarMega53 from "../assets/imgs/fone sem fio starmega st-162 5.3.png";
import caboV8 from "../assets/imgs/cabo peining v.8.png";
import caboTypeCTY from "../assets/imgs/cabo  tipo - C TY.png";
import carregadorV8Kapbom from "../assets/imgs/carregador kapbom 5.1A Fast charger.png";
import carregadorTypeCLehmix from "../assets/imgs/carregador lehmox fastcharger le512.3.png";
import pelicula from "../assets/imgs/peliculas.png";

export const images = {
  foneP2KapBom,
  foneP2LehMox,
  foneBluetoothStarMega,
  foneBluetoothStarMega53,
  caboV8,
  caboTypeCTY,
  carregadorV8Kapbom,
  carregadorTypeCLehmix,
  pelicula,
};

export const cores = [
  [{ classe: "" }, { classe: "" }],
  [{ classe: "bg-black" }, { classe: "bg-white " }],
  [
    { classe: "bg-white" },
    { classe: "bg-red-500" },

    { classe: "bg-black" },
    { classe: "bg-blue-500" },
    { classe: "bg-yellow-500" },
  ],
  [{ classe: "bg-blue-500" }, { classe: "bg-black" }],
  [{ classe: "bg-black" }],
  [{ classe: "bg-pink-500" }, { classe: "bg-white " }, { classe: "bg-black" }],
];

const products = [
  {
    categoria: "Películas",
    itens: [
      {
        id: 1,
        title: "Película 3D Samsung A01",
        description: "Vidro 3D com alta transparência e proteção diária.",
        preco: 3,
        img: [images.pelicula, images.pelicula],
        cores: cores[0],
      },
      {
        id: 2,
        title: "Película 3D Samsung A01 Core",
        description: "Proteção total com encaixe perfeito.",
        preco: 3,
        img: [images.pelicula, images.pelicula, images.pelicula],
        cores: cores[0],
      },
      {
        id: 3,
        title: "Película 3D Samsung A10",
        description: "Vidro resistente contra riscos.",
        preco: 3,
        img: [images.pelicula],
        cores: cores[0],
      },
      {
        id: 4,
        title: "Película 3D Samsung A11",
        description: "Alta durabilidade para uso diário.",
        preco: 3,
        img: [images.pelicula],
        cores: cores[0],
      },
      {
        id: 5,
        title: "Película 3D Samsung A20",
        description: "Proteção premium sem perder sensibilidade.",
        preco: 3,
        img: [images.pelicula],
        cores: cores[0],
      },
      {
        id: 6,
        title: "Película 3D Samsung A21",
        description: "Vidro reforçado com toque suave.",
        preco: 3,
        img: [images.pelicula],
        cores: cores[0],
      },
      {
        id: 7,
        title: "Película 3D Samsung A30",
        description: "Proteção completa da tela.",
        preco: 3,
        img: [images.pelicula],
        cores: cores[0],
      },
      {
        id: 8,
        title: "Película 3D Samsung A50",
        description: "Vidro durável e transparente.",
        preco: 3,
        img: [images.pelicula],
        cores: cores[0],
      },
      {
        id: 9,
        title: "Película 3D Samsung A54",
        description: "Proteção contra riscos e impactos leves.",
        preco: 3,
        img: [images.pelicula],
        cores: cores[0],
      },
      {
        id: 10,
        title: "Película 3D Redmi 9",
        description: "Cobertura total com encaixe perfeito.",
        preco: 3,
        img: [images.pelicula],
        cores: cores[0],
      },
      {
        id: 11,
        title: "Película 3D Redmi 10",
        description: "Alta resistência e transparência.",
        preco: 3,
        img: [images.pelicula],
        cores: cores[0],
      },
      {
        id: 12,
        title: "Película 3D Redmi Note 10",
        description: "Proteção premium para tela.",
        preco: 3,
        img: [images.pelicula],
        cores: cores[0],
      },
      {
        id: 13,
        title: "Película 3D Redmi Note 11",
        description: "Vidro reforçado para uso diário.",
        preco: 3,
        img: [images.pelicula],
        cores: cores[0],
      },
      {
        id: 14,
        title: "Película 3D Redmi Note 12",
        description: "Proteção eficiente e durável.",
        preco: 3,
        img: [images.pelicula],
        cores: cores[0],
      },
      {
        id: 15,
        title: "Película 3D iPhone XR",
        description: "Alta transparência e proteção.",
        preco: 3,
        img: [images.pelicula],
        cores: cores[0],
      },
      {
        id: 16,
        title: "Película 3D iPhone 11",
        description: "Proteção diária sem perder o toque.",
        preco: 3,
        img: [images.pelicula],
        cores: cores[0],
      },
      {
        id: 17,
        title: "Película 3D iPhone 12",
        description: "Vidro resistente e durável.",
        preco: 3,
        img: [images.pelicula],
        cores: cores[0],
      },
      {
        id: 18,
        title: "Película 3D iPhone 13",
        description: "Proteção premium contra riscos.",
        preco: 3,
        img: [images.pelicula],
        cores: cores[0],
      },
      {
        id: 19,
        title: "Película 3D iPhone 14",
        description: "Alta durabilidade e encaixe perfeito.",
        preco: 3,
        img: [images.pelicula],
        cores: cores[0],
      },
      {
        id: 20,
        title: "Película 3D iPhone 14 Plus",
        description: "Proteção completa da tela.",
        preco: 3,
        img: [images.pelicula],
        cores: cores[0],
      },
    ],
  },

  {
    categoria: "Cabos",
    itens: [
      {
        id: 21,
        title: "Cabo V8 Peining",
        description: "Carga e dados para uso diário.",
        preco: 6,
        img: [images.caboV8],
        cores: cores[2],
      },
      {
        id: 22,
        title: "Cabo V8 Turbo",
        description: "Alta durabilidade e carga rápida.",
        preco: 5.5,
        img: [images.caboV8],
        cores: cores[2],
      },
      {
        id: 23,
        title: "Cabo V8 Reforçado",
        description: "Resistente a dobras.",
        preco: 5,
        img: [images.caboV8],
        cores: cores[2],
      },
      {
        id: 24,
        title: "Cabo Tipo-C TY",
        description: "Compatível com celulares modernos.",
        preco: 4,
        img: [images.caboTypeCTY],
        cores: cores[4],
      },
      {
        id: 25,
        title: "Cabo Tipo-C Turbo",
        description: "Carga rápida e estável.",
        preco: 4.5,
        img: [images.caboTypeCTY],
        cores: cores[4],
      },
      {
        id: 26,
        title: "Cabo Tipo-C Reforçado",
        description: "Alta resistência.",
        preco: 4,
        img: [images.caboTypeCTY],
        cores: cores[0],
      },
      {
        id: 27,
        title: "Cabo V8 Longo",
        description: "Maior alcance para uso confortável.",
        preco: 6.5,
        img: [images.caboV8],
        cores: cores[1],
      },
      {
        id: 28,
        title: "Cabo Tipo-C Longo",
        description: "Mais liberdade no uso.",
        preco: 5,
        img: [images.caboTypeCTY],
        cores: cores[2],
      },
      {
        id: 29,
        title: "Cabo V8 Simples",
        description: "Uso básico diário.",
        preco: 4.5,
        img: [images.caboV8],
        cores: cores[3],
      },
      {
        id: 30,
        title: "Cabo Tipo-C Simples",
        description: "Carga padrão.",
        preco: 3.8,
        img: [images.caboTypeCTY],
        cores: cores[4],
      },
      {
        id: 31,
        title: "Cabo V8 Premium",
        description: "Alta qualidade e durabilidade.",
        preco: 7,
        img: [images.caboV8],
        cores: cores[0],
      },
      {
        id: 32,
        title: "Cabo Tipo-C Premium",
        description: "Fast charge confiável.",
        preco: 6,
        img: [images.caboTypeCTY],
        cores: cores[1],
      },
    ],
  },

  {
    categoria: "Carregadores",
    itens: [
      {
        id: 33,
        title: "Carregador LehMox 30W",
        description: "Fast charge seguro.",
        preco: 16.5,
        img: [images.carregadorTypeCLehmix],
        cores: cores[0],
      },
      {
        id: 34,
        title: "Carregador LehMox 20W",
        description: "Carga rápida eficiente.",
        preco: 14,
        img: [images.carregadorTypeCLehmix],
        cores: cores[1],
      },
      {
        id: 35,
        title: "Carregador Kapbom 5.1A",
        description: "Carregamento turbo.",
        preco: 5.5,
        img: [images.carregadorV8Kapbom],
        cores: cores[2],
      },
      {
        id: 36,
        title: "Carregador Kapbom Duplo",
        description: "Duas portas USB.",
        preco: 7,
        img: [images.carregadorV8Kapbom],
        cores: cores[3],
      },
      {
        id: 37,
        title: "Carregador Kapbom Simples",
        description: "Uso básico.",
        preco: 4.5,
        img: [images.carregadorV8Kapbom],
        cores: cores[4],
      },
      {
        id: 38,
        title: "Carregador Tipo-C Turbo",
        description: "Alta potência.",
        preco: 15,
        img: [images.carregadorTypeCLehmix],
        cores: cores[0],
      },
      {
        id: 39,
        title: "Carregador Tipo-C Premium",
        description: "Alta eficiência.",
        preco: 18,
        img: [images.carregadorTypeCLehmix],
        cores: cores[1],
      },
      {
        id: 40,
        title: "Carregador V8 Premium",
        description: "Qualidade superior.",
        preco: 8,
        img: [images.carregadorV8Kapbom],
        cores: cores[2],
      },
      {
        id: 41,
        title: "Carregador V8 Compacto",
        description: "Portátil.",
        preco: 5,
        img: [images.carregadorV8Kapbom],
        cores: cores[3],
      },
      {
        id: 42,
        title: "Carregador Tipo-C Compacto",
        description: "Leve e eficiente.",
        preco: 13,
        img: [images.carregadorTypeCLehmix],
        cores: cores[4],
      },
    ],
  },

  {
    categoria: "Fones de Ouvido",
    itens: [
      {
        id: 43,
        title: "Fone P2 LehMox",
        description: "Som limpo para músicas e chamadas.",
        preco: 4,
        img: [images.foneP2LehMox],
        cores: cores[0],
      },
      {
        id: 44,
        title: "Fone P2 Kapbom",
        description: "Com microfone integrado.",
        preco: 3.5,
        img: [images.foneP2KapBom],
        cores: cores[1],
      },
      {
        id: 45,
        title: "Fone P2 Reforçado",
        description: "Alta durabilidade.",
        preco: 5,
        img: [images.foneP2LehMox],
        cores: cores[2],
      },
      {
        id: 46,
        title: "Fone Bluetooth ST-158",
        description: "Conexão estável.",
        preco: 19,
        img: [images.foneBluetoothStarMega],
        cores: cores[3],
      },
      {
        id: 47,
        title: "Fone Bluetooth ST-162",
        description: "Bluetooth 5.3.",
        preco: 22.5,
        img: [images.foneBluetoothStarMega53],
        cores: cores[4],
      },
      {
        id: 48,
        title: "Fone Bluetooth Compact",
        description: "Leve e prático.",
        preco: 18,
        img: [images.foneBluetoothStarMega],
        cores: cores[0],
      },
      {
        id: 49,
        title: "Fone Bluetooth Premium",
        description: "Som limpo.",
        preco: 24,
        img: [images.foneBluetoothStarMega53],
        cores: cores[1],
      },
      {
        id: 50,
        title: "Fone P2 Simples",
        description: "Uso diário.",
        preco: 3,
        img: [images.foneP2KapBom],
        cores: cores[2],
      },
      {
        id: 51,
        title: "Fone P2 Bass",
        description: "Graves reforçados.",
        preco: 5.5,
        img: [images.foneP2LehMox],
        cores: cores[3],
      },
      {
        id: 52,
        title: "Fone Bluetooth Básico",
        description: "Custo-benefício.",
        preco: 17,
        img: [images.foneBluetoothStarMega],
        cores: cores[4],
      },
    ],
  },
];

export default products;
export const OpcoesComRating = products.map((categoria) => ({
  ...categoria,
  itens: categoria.itens.map((produto) => ({
    ...produto,
    rating: {
      media: 4.7,
      totalAvaliacoes: 254,
    },
  })),
}));

// import carne from "../assets/imgs/download.jpeg";
// import biscoito from "../assets/imgs/biscoito.jpeg";
// import leite from "../assets/imgs/leite.jpeg";
// import maca from "../assets/imgs/maca.jpeg";
// import melancia from "../assets/imgs/melancia.jpeg ";
// import pao from "../assets/imgs/pao.jpeg";
// import cafe from "../assets/imgs/santaclara.jpeg";
// const Opcoes = [
//   {
//     categoria: "Fones",
//     itens: [
//       {
//         id: 1,
//         title: "Queijo Mussarela",
//         produto: "Queijo Mussarela",
//         description: "Queijo macio ideal para pizzas.",
//         preco: 32.9,
//         img: leite,
//       },
//       {
//         id: 2,
//         title: "Leite Integral",
//         produto: "Leite Integral",
//         description: "Leite integral fresco.",
//         preco: 6.5,
//         img: leite,
//       },
//       {
//         id: 3,
//         title: "Iogurte Natural",
//         produto: "Iogurte Natural",
//         description: "Iogurte sem açúcar.",
//         preco: 4.9,
//         img: leite,
//       },
//       {
//         id: 4,
//         title: "Manteiga",
//         produto: "Manteiga",
//         description: "Manteiga cremosa.",
//         preco: 9.9,
//         img: leite,
//       },
//       {
//         id: 5,
//         title: "Requeijão",
//         produto: "Requeijão",
//         description: "Requeijão tradicional.",
//         preco: 7.9,
//         img: leite,
//       },
//       {
//         id: 6,
//         title: "Queijo Prato",
//         produto: "Queijo Prato",
//         description: "Queijo suave.",
//         preco: 28.9,
//         img: leite,
//       },
//       {
//         id: 7,
//         title: "Creme de Leite",
//         produto: "Creme de Leite",
//         description: "Ideal para receitas.",
//         preco: 4.2,
//         img: leite,
//       },
//       {
//         id: 8,
//         title: "Leite Desnatado",
//         produto: "Leite Desnatado",
//         description: "Menos gordura.",
//         preco: 6.3,
//         img: leite,
//       },
//     ],
//   },
//   {
//     categoria: "Café",
//     itens: [
//       {
//         id: 9,
//         title: "Café Tradicional",
//         produto: "Café Tradicional",
//         description: "Aromático e encorpado.",
//         preco: 18.9,
//         img: cafe,
//       },
//       {
//         id: 10,
//         title: "Café Extra Forte",
//         produto: "Café Extra Forte",
//         description: "Sabor intenso.",
//         preco: 21.9,
//         img: cafe,
//       },
//       {
//         id: 11,
//         title: "Café Gourmet",
//         produto: "Café Gourmet",
//         description: "Grãos selecionados.",
//         preco: 29.9,
//         img: cafe,
//       },
//       {
//         id: 12,
//         title: "Café Solúvel",
//         produto: "Café Solúvel",
//         description: "Praticidade no preparo.",
//         preco: 14.9,
//         img: cafe,
//       },
//       {
//         id: 13,
//         title: "Café Descafeinado",
//         produto: "Café Descafeinado",
//         description: "Sem cafeína.",
//         preco: 22.9,
//         img: cafe,
//       },
//       {
//         id: 14,
//         title: "Café em Cápsula",
//         produto: "Café em Cápsula",
//         description: "Compatível com máquinas.",
//         preco: 34.9,
//         img: cafe,
//       },
//       {
//         id: 15,
//         title: "Café Orgânico",
//         produto: "Café Orgânico",
//         description: "Produção sustentável.",
//         preco: 31.9,
//         img: cafe,
//       },
//       {
//         id: 16,
//         title: "Café Torrado",
//         produto: "Café Torrado",
//         description: "Torra média.",
//         preco: 19.9,
//         img: cafe,
//       },
//     ],
//   },
//   {
//     categoria: "Frutas",
//     itens: [
//       {
//         id: 17,
//         title: "Maçã",
//         produto: "Maçã",
//         description: "Crocante e fresca.",
//         preco: 7.5,
//         img: maca,
//       },
//       {
//         id: 18,
//         title: "Banana",
//         produto: "Banana",
//         description: "Fonte de energia.",
//         preco: 6.2,
//         img: maca,
//       },
//       {
//         id: 19,
//         title: "Uva",
//         produto: "Uva",
//         description: "Doce e suculenta.",
//         preco: 12.9,
//         img: maca,
//       },
//       {
//         id: 20,
//         title: "Laranja",
//         produto: "Laranja",
//         description: "Rica em vitamina C.",
//         preco: 5.9,
//         img: maca,
//       },
//       {
//         id: 21,
//         title: "Manga",
//         produto: "Manga",
//         description: "Doce e tropical.",
//         preco: 8.9,
//         img: maca,
//       },
//       {
//         id: 22,
//         title: "Abacaxi",
//         produto: "Abacaxi",
//         description: "Refrescante.",
//         preco: 9.5,
//         img: maca,
//       },
//       {
//         id: 23,
//         title: "Pera",
//         produto: "Pera",
//         description: "Textura macia.",
//         preco: 8.2,
//         img: maca,
//       },
//       {
//         id: 24,
//         title: "Melancia",
//         produto: "Melancia",
//         description: "Ideal para o calor.",
//         preco: 14.9,
//         img: maca,
//       },
//     ],
//   },
//   {
//     categoria: "Biscoitos",
//     itens: [
//       {
//         id: 25,
//         title: "Biscoito Recheado",
//         produto: "Biscoito Recheado",
//         description: "Recheio cremoso.",
//         preco: 3.9,
//         img: biscoito,
//       },
//       {
//         id: 26,
//         title: "Biscoito Água e Sal",
//         produto: "Biscoito Água e Sal",
//         description: "Leve e crocante.",
//         preco: 4.5,
//         img: biscoito,
//       },
//       {
//         id: 27,
//         title: "Biscoito Integral",
//         produto: "Biscoito Integral",
//         description: "Mais fibras.",
//         preco: 5.9,
//         img: biscoito,
//       },
//       {
//         id: 28,
//         title: "Biscoito Chocolate",
//         produto: "Biscoito Chocolate",
//         description: "Sabor intenso.",
//         preco: 4.9,
//         img: biscoito,
//       },
//       {
//         id: 29,
//         title: "Biscoito Maisena",
//         produto: "Biscoito Maisena",
//         description: "Clássico.",
//         preco: 4.2,
//         img: biscoito,
//       },
//       {
//         id: 30,
//         title: "Biscoito Aveia",
//         produto: "Biscoito Aveia",
//         description: "Opção saudável.",
//         preco: 6.9,
//         img: biscoito,
//       },
//       {
//         id: 31,
//         title: "Biscoito Coco",
//         produto: "Biscoito Coco",
//         description: "Aroma natural.",
//         preco: 5.5,
//         img: biscoito,
//       },
//       {
//         id: 32,
//         title: "Biscoito Manteiga",
//         produto: "Biscoito Manteiga",
//         description: "Sabor caseiro.",
//         preco: 6.2,
//         img: biscoito,
//       },
//     ],
//   },
//   {
//     categoria: "Bebidas",
//     itens: [
//       {
//         id: 33,
//         title: "Refrigerante Cola",
//         produto: "Refrigerante Cola",
//         description: "Tradicional.",
//         preco: 7.9,
//         img: "refrigerante-cola.png",
//       },
//       {
//         id: 34,
//         title: "Suco de Laranja",
//         produto: "Suco de Laranja",
//         description: "Natural.",
//         preco: 6.5,
//         img: "suco-laranja.png",
//       },
//       {
//         id: 35,
//         title: "Suco de Uva",
//         produto: "Suco de Uva",
//         description: "Integral.",
//         preco: 8.9,
//         img: "suco-uva.png",
//       },
//       {
//         id: 36,
//         title: "Água Mineral",
//         produto: "Água Mineral",
//         description: "Sem gás.",
//         preco: 2.5,
//         img: "agua.png",
//       },
//       {
//         id: 37,
//         title: "Chá Gelado",
//         produto: "Chá Gelado",
//         description: "Refrescante.",
//         preco: 5.9,
//         img: "cha-gelado.png",
//       },
//       {
//         id: 38,
//         title: "Energético",
//         produto: "Energético",
//         description: "Mais energia.",
//         preco: 9.9,
//         img: "energetico.png",
//       },
//       {
//         id: 39,
//         title: "Isotônico",
//         produto: "Isotônico",
//         description: "Reposição energética.",
//         preco: 7.2,
//         img: "isotonico.png",
//       },
//       {
//         id: 40,
//         title: "Água de Coco",
//         produto: "Água de Coco",
//         description: "Natural.",
//         preco: 6.8,
//         img: "agua-coco.png",
//       },
//     ],
//   },
//   {
//     categoria: "Padaria",
//     itens: [
//       {
//         id: 41,
//         title: "Pão Francês",
//         produto: "Pão Francês",
//         description: "Fresco.",
//         preco: 0.8,
//         img: "pao-frances.png",
//       },
//       {
//         id: 42,
//         title: "Pão Integral",
//         produto: "Pão Integral",
//         description: "Rico em fibras.",
//         preco: 7.9,
//         img: "pao-integral.png",
//       },
//       {
//         id: 43,
//         title: "Bolo de Chocolate",
//         produto: "Bolo de Chocolate",
//         description: "Macio.",
//         preco: 14.9,
//         img: "bolo-chocolate.png",
//       },
//       {
//         id: 44,
//         title: "Bolo de Cenoura",
//         produto: "Bolo de Cenoura",
//         description: "Com cobertura.",
//         preco: 13.9,
//         img: "bolo-cenoura.png",
//       },
//       {
//         id: 45,
//         title: "Croissant",
//         produto: "Croissant",
//         description: "Folhado.",
//         preco: 6.5,
//         img: "croissant.png",
//       },
//       {
//         id: 46,
//         title: "Pão de Queijo",
//         produto: "Pão de Queijo",
//         description: "Tradicional.",
//         preco: 9.9,
//         img: "pao-queijo.png",
//       },
//       {
//         id: 47,
//         title: "Sonho",
//         produto: "Sonho",
//         description: "Recheado.",
//         preco: 5.9,
//         img: "sonho.png",
//       },
//       {
//         id: 48,
//         title: "Torta Doce",
//         produto: "Torta Doce",
//         description: "Sabor variado.",
//         preco: 18.9,
//         img: "torta.png",
//       },
//     ],
//   },
//   {
//     categoria: "Carnes",
//     itens: [
//       {
//         id: 49,
//         title: "Carne Bovina",
//         produto: "Carne Bovina",
//         description: "Corte macio.",
//         preco: 42.9,
//         img: "carne-bovina.png",
//       },
//       {
//         id: 50,
//         title: "Frango",
//         produto: "Frango",
//         description: "Fresco.",
//         preco: 16.9,
//         img: "frango.png",
//       },
//       {
//         id: 51,
//         title: "Linguiça",
//         produto: "Linguiça",
//         description: "Temperada.",
//         preco: 19.9,
//         img: "linguica.png",
//       },
//       {
//         id: 52,
//         title: "Carne Suína",
//         produto: "Carne Suína",
//         description: "Saborosa.",
//         preco: 24.9,
//         img: "carne-suina.png",
//       },
//       {
//         id: 53,
//         title: "Peixe",
//         produto: "Peixe",
//         description: "Fresco.",
//         preco: 29.9,
//         img: "peixe.png",
//       },
//       {
//         id: 54,
//         title: "Costela",
//         produto: "Costela",
//         description: "Ideal para churrasco.",
//         preco: 39.9,
//         img: "costela.png",
//       },
//       {
//         id: 55,
//         title: "Bacon",
//         produto: "Bacon",
//         description: "Defumado.",
//         preco: 21.9,
//         img: "bacon.png",
//       },
//       {
//         id: 56,
//         title: "Hambúrguer",
//         produto: "Hambúrguer",
//         description: "Artesanal.",
//         preco: 17.9,
//         img: "hamburguer.png",
//       },
//     ],
//   },
//   {
//     categoria: "Limpeza",
//     itens: [
//       {
//         id: 57,
//         title: "Detergente",
//         produto: "Detergente",
//         description: "Limpeza eficiente.",
//         preco: 2.9,
//         img: "detergente.png",
//       },
//       {
//         id: 58,
//         title: "Sabão em Pó",
//         produto: "Sabão em Pó",
//         description: "Rende mais.",
//         preco: 12.9,
//         img: "sabao-po.png",
//       },
//       {
//         id: 59,
//         title: "Desinfetante",
//         produto: "Desinfetante",
//         description: "Aroma agradável.",
//         preco: 6.9,
//         img: "desinfetante.png",
//       },
//       {
//         id: 60,
//         title: "Álcool",
//         produto: "Álcool",
//         description: "Higienização.",
//         preco: 5.5,
//         img: "alcool.png",
//       },
//       {
//         id: 61,
//         title: "Esponja",
//         produto: "Esponja",
//         description: "Multiuso.",
//         preco: 3.2,
//         img: "esponja.png",
//       },
//       {
//         id: 62,
//         title: "Limpador Multiuso",
//         produto: "Limpador Multiuso",
//         description: "Prático.",
//         preco: 7.9,
//         img: "multiuso.png",
//       },
//       {
//         id: 63,
//         title: "Amaciante",
//         produto: "Amaciante",
//         description: "Perfume duradouro.",
//         preco: 11.9,
//         img: "amaciante.png",
//       },
//       {
//         id: 64,
//         title: "Papel Toalha",
//         produto: "Papel Toalha",
//         description: "Alta absorção.",
//         preco: 8.9,
//         img: "papel-toalha.png",
//       },
//     ],
//   },
// ];
// export default Opcoes;
